# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ui.mplwidget import MplWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.SMEAR_tab = QtWidgets.QWidget()
        self.SMEAR_tab.setObjectName("SMEAR_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SMEAR_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SMEAR_plot = MplWidget(self.SMEAR_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SMEAR_plot.sizePolicy().hasHeightForWidth())
        self.SMEAR_plot.setSizePolicy(sizePolicy)
        self.SMEAR_plot.setAutoFillBackground(True)
        self.SMEAR_plot.setObjectName("SMEAR_plot")
        self.gridLayout_2.addWidget(self.SMEAR_plot, 0, 0, 4, 1)
        self.SMEAR_gas_group = QtWidgets.QGroupBox(self.SMEAR_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SMEAR_gas_group.sizePolicy().hasHeightForWidth()
        )
        self.SMEAR_gas_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SMEAR_gas_group.setFont(font)
        self.SMEAR_gas_group.setObjectName("SMEAR_gas_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SMEAR_gas_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SMEAR_co2_radio_button = QtWidgets.QRadioButton(self.SMEAR_gas_group)
        self.SMEAR_co2_radio_button.setChecked(True)
        self.SMEAR_co2_radio_button.setObjectName("SMEAR_co2_radio_button")
        self.gridLayout_3.addWidget(self.SMEAR_co2_radio_button, 0, 0, 1, 1)
        self.SMEAR_so2_radio_button = QtWidgets.QRadioButton(self.SMEAR_gas_group)
        self.SMEAR_so2_radio_button.setObjectName("SMEAR_so2_radio_button")
        self.gridLayout_3.addWidget(self.SMEAR_so2_radio_button, 0, 1, 1, 1)
        self.SMEAR_no_radio_button = QtWidgets.QRadioButton(self.SMEAR_gas_group)
        self.SMEAR_no_radio_button.setObjectName("SMEAR_no_radio_button")
        self.gridLayout_3.addWidget(self.SMEAR_no_radio_button, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.SMEAR_gas_group, 0, 1, 1, 1)
        self.SMEAR_stations_group = QtWidgets.QGroupBox(self.SMEAR_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SMEAR_stations_group.sizePolicy().hasHeightForWidth()
        )
        self.SMEAR_stations_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SMEAR_stations_group.setFont(font)
        self.SMEAR_stations_group.setObjectName("SMEAR_stations_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SMEAR_stations_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SMEAR_stations_list = QtWidgets.QListWidget(self.SMEAR_stations_group)
        self.SMEAR_stations_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.SMEAR_stations_list.setWordWrap(True)
        self.SMEAR_stations_list.setObjectName("SMEAR_stations_list")
        self.verticalLayout_2.addWidget(self.SMEAR_stations_list)
        self.gridLayout_2.addWidget(self.SMEAR_stations_group, 1, 1, 1, 1)
        self.SMEAR_time_group = QtWidgets.QGroupBox(self.SMEAR_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SMEAR_time_group.sizePolicy().hasHeightForWidth()
        )
        self.SMEAR_time_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SMEAR_time_group.setFont(font)
        self.SMEAR_time_group.setObjectName("SMEAR_time_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SMEAR_time_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SMEAR_start_time_label = QtWidgets.QLabel(self.SMEAR_time_group)
        self.SMEAR_start_time_label.setObjectName("SMEAR_start_time_label")
        self.gridLayout.addWidget(self.SMEAR_start_time_label, 0, 0, 1, 1)
        self.SMEAR_end_time_edit = QtWidgets.QDateTimeEdit(self.SMEAR_time_group)
        self.SMEAR_end_time_edit.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(20, 0, 0))
        )
        self.SMEAR_end_time_edit.setCalendarPopup(True)
        self.SMEAR_end_time_edit.setObjectName("SMEAR_end_time_edit")
        self.gridLayout.addWidget(self.SMEAR_end_time_edit, 1, 1, 1, 1)
        self.SMEAR_start_time_edit = QtWidgets.QDateTimeEdit(self.SMEAR_time_group)
        self.SMEAR_start_time_edit.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(14, 0, 0))
        )
        self.SMEAR_start_time_edit.setCalendarPopup(True)
        self.SMEAR_start_time_edit.setObjectName("SMEAR_start_time_edit")
        self.gridLayout.addWidget(self.SMEAR_start_time_edit, 0, 1, 1, 1)
        self.SMEAR_end_time_label = QtWidgets.QLabel(self.SMEAR_time_group)
        self.SMEAR_end_time_label.setObjectName("SMEAR_end_time_label")
        self.gridLayout.addWidget(self.SMEAR_end_time_label, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.SMEAR_time_group, 2, 1, 1, 1)
        self.SMEAR_aggregation_group = QtWidgets.QGroupBox(self.SMEAR_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SMEAR_aggregation_group.sizePolicy().hasHeightForWidth()
        )
        self.SMEAR_aggregation_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SMEAR_aggregation_group.setFont(font)
        self.SMEAR_aggregation_group.setObjectName("SMEAR_aggregation_group")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.SMEAR_aggregation_group)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.SMEAR_none_radio_button = QtWidgets.QRadioButton(
            self.SMEAR_aggregation_group
        )
        self.SMEAR_none_radio_button.setChecked(True)
        self.SMEAR_none_radio_button.setObjectName("SMEAR_none_radio_button")
        self.gridLayout_12.addWidget(self.SMEAR_none_radio_button, 0, 0, 1, 1)
        self.SMEAR_min_radio_button = QtWidgets.QRadioButton(
            self.SMEAR_aggregation_group
        )
        self.SMEAR_min_radio_button.setObjectName("SMEAR_min_radio_button")
        self.gridLayout_12.addWidget(self.SMEAR_min_radio_button, 0, 1, 1, 1)
        self.SMEAR_max_radio_button = QtWidgets.QRadioButton(
            self.SMEAR_aggregation_group
        )
        self.SMEAR_max_radio_button.setObjectName("SMEAR_max_radio_button")
        self.gridLayout_12.addWidget(self.SMEAR_max_radio_button, 0, 2, 1, 1)
        self.SMEAR_avg_radio_button = QtWidgets.QRadioButton(
            self.SMEAR_aggregation_group
        )
        self.SMEAR_avg_radio_button.setObjectName("SMEAR_avg_radio_button")
        self.gridLayout_12.addWidget(self.SMEAR_avg_radio_button, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.SMEAR_aggregation_group, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SMEAR_summary_button = QtWidgets.QPushButton(self.SMEAR_tab)
        self.SMEAR_summary_button.setEnabled(False)
        self.SMEAR_summary_button.setObjectName("SMEAR_summary_button")
        self.horizontalLayout_4.addWidget(self.SMEAR_summary_button)
        self.SMEAR_save_plot_button = QtWidgets.QPushButton(self.SMEAR_tab)
        self.SMEAR_save_plot_button.setEnabled(False)
        self.SMEAR_save_plot_button.setObjectName("SMEAR_save_plot_button")
        self.horizontalLayout_4.addWidget(self.SMEAR_save_plot_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SMEAR_reset_button = QtWidgets.QPushButton(self.SMEAR_tab)
        self.SMEAR_reset_button.setObjectName("SMEAR_reset_button")
        self.horizontalLayout.addWidget(self.SMEAR_reset_button)
        self.SMEAR_fetch_button = QtWidgets.QPushButton(self.SMEAR_tab)
        self.SMEAR_fetch_button.setObjectName("SMEAR_fetch_button")
        self.horizontalLayout.addWidget(self.SMEAR_fetch_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.tabWidget.addTab(self.SMEAR_tab, "")
        self.STATFI_tab = QtWidgets.QWidget()
        self.STATFI_tab.setObjectName("STATFI_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.STATFI_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.STATFI_reset_button = QtWidgets.QPushButton(self.STATFI_tab)
        self.STATFI_reset_button.setObjectName("STATFI_reset_button")
        self.gridLayout_5.addWidget(self.STATFI_reset_button, 3, 1, 1, 1)
        self.STATFI_figures_group = QtWidgets.QGroupBox(self.STATFI_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.STATFI_figures_group.setFont(font)
        self.STATFI_figures_group.setObjectName("STATFI_figures_group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.STATFI_figures_group)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.STATFI_figures_list = QtWidgets.QListWidget(self.STATFI_figures_group)
        self.STATFI_figures_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.STATFI_figures_list.setWordWrap(True)
        self.STATFI_figures_list.setObjectName("STATFI_figures_list")
        self.gridLayout_4.addWidget(self.STATFI_figures_list, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.STATFI_figures_group, 0, 1, 1, 2)
        self.STATFI_fetch_button = QtWidgets.QPushButton(self.STATFI_tab)
        self.STATFI_fetch_button.setObjectName("STATFI_fetch_button")
        self.gridLayout_5.addWidget(self.STATFI_fetch_button, 3, 2, 1, 1)
        self.STATFI_visualization_group = QtWidgets.QGroupBox(self.STATFI_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.STATFI_visualization_group.setFont(font)
        self.STATFI_visualization_group.setObjectName("STATFI_visualization_group")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.STATFI_visualization_group)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.STATFI_bar_chart_radio_button = QtWidgets.QRadioButton(
            self.STATFI_visualization_group
        )
        self.STATFI_bar_chart_radio_button.setObjectName(
            "STATFI_bar_chart_radio_button"
        )
        self.gridLayout_7.addWidget(self.STATFI_bar_chart_radio_button, 0, 0, 1, 1)
        self.STATFI_line_graph_radio_button = QtWidgets.QRadioButton(
            self.STATFI_visualization_group
        )
        self.STATFI_line_graph_radio_button.setChecked(True)
        self.STATFI_line_graph_radio_button.setObjectName(
            "STATFI_line_graph_radio_button"
        )
        self.gridLayout_7.addWidget(self.STATFI_line_graph_radio_button, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.STATFI_visualization_group, 2, 1, 1, 2)
        self.STATFI_years_group = QtWidgets.QGroupBox(self.STATFI_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.STATFI_years_group.setFont(font)
        self.STATFI_years_group.setObjectName("STATFI_years_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.STATFI_years_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.STATFI_years_list = QtWidgets.QListWidget(self.STATFI_years_group)
        self.STATFI_years_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.STATFI_years_list.setWordWrap(True)
        self.STATFI_years_list.setObjectName("STATFI_years_list")
        self.gridLayout_6.addWidget(self.STATFI_years_list, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.STATFI_years_group, 1, 1, 1, 2)
        self.STATFI_plot = MplWidget(self.STATFI_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.STATFI_plot.sizePolicy().hasHeightForWidth())
        self.STATFI_plot.setSizePolicy(sizePolicy)
        self.STATFI_plot.setAutoFillBackground(True)
        self.STATFI_plot.setObjectName("STATFI_plot")
        self.gridLayout_5.addWidget(self.STATFI_plot, 0, 0, 3, 1)
        self.STATFI_save_plot_button = QtWidgets.QPushButton(self.STATFI_tab)
        self.STATFI_save_plot_button.setEnabled(False)
        self.STATFI_save_plot_button.setObjectName("STATFI_save_plot_button")
        self.gridLayout_5.addWidget(self.STATFI_save_plot_button, 3, 0, 1, 1)
        self.tabWidget.addTab(self.STATFI_tab, "")
        self.compare_tab = QtWidgets.QWidget()
        self.compare_tab.setObjectName("compare_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.compare_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.compare_STATFI_figures_group = QtWidgets.QGroupBox(self.compare_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compare_STATFI_figures_group.sizePolicy().hasHeightForWidth()
        )
        self.compare_STATFI_figures_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compare_STATFI_figures_group.setFont(font)
        self.compare_STATFI_figures_group.setObjectName("compare_STATFI_figures_group")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.compare_STATFI_figures_group)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.compare_STATFI_figures_list = QtWidgets.QListWidget(
            self.compare_STATFI_figures_group
        )
        self.compare_STATFI_figures_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.compare_STATFI_figures_list.setWordWrap(True)
        self.compare_STATFI_figures_list.setObjectName("compare_STATFI_figures_list")
        self.gridLayout_10.addWidget(self.compare_STATFI_figures_list, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.compare_STATFI_figures_group, 0, 1, 1, 1)
        self.compare_STATFI_years_group = QtWidgets.QGroupBox(self.compare_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compare_STATFI_years_group.sizePolicy().hasHeightForWidth()
        )
        self.compare_STATFI_years_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compare_STATFI_years_group.setFont(font)
        self.compare_STATFI_years_group.setObjectName("compare_STATFI_years_group")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.compare_STATFI_years_group)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.compare_STATFI_years_list = QtWidgets.QListWidget(
            self.compare_STATFI_years_group
        )
        self.compare_STATFI_years_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.compare_STATFI_years_list.setWordWrap(True)
        self.compare_STATFI_years_list.setObjectName("compare_STATFI_years_list")
        self.gridLayout_9.addWidget(self.compare_STATFI_years_list, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.compare_STATFI_years_group, 1, 1, 1, 1)
        self.compare_SMEAR_gas_group = QtWidgets.QGroupBox(self.compare_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compare_SMEAR_gas_group.sizePolicy().hasHeightForWidth()
        )
        self.compare_SMEAR_gas_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compare_SMEAR_gas_group.setFont(font)
        self.compare_SMEAR_gas_group.setObjectName("compare_SMEAR_gas_group")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.compare_SMEAR_gas_group)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.compare_co2_radio_button = QtWidgets.QRadioButton(
            self.compare_SMEAR_gas_group
        )
        self.compare_co2_radio_button.setChecked(True)
        self.compare_co2_radio_button.setObjectName("compare_co2_radio_button")
        self.gridLayout_11.addWidget(self.compare_co2_radio_button, 0, 0, 1, 1)
        self.compare_so2_radio_button = QtWidgets.QRadioButton(
            self.compare_SMEAR_gas_group
        )
        self.compare_so2_radio_button.setObjectName("compare_so2_radio_button")
        self.gridLayout_11.addWidget(self.compare_so2_radio_button, 0, 1, 1, 1)
        self.compare_no_radio_button = QtWidgets.QRadioButton(
            self.compare_SMEAR_gas_group
        )
        self.compare_no_radio_button.setObjectName("compare_no_radio_button")
        self.gridLayout_11.addWidget(self.compare_no_radio_button, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.compare_SMEAR_gas_group, 2, 1, 1, 1)
        self.compare_SMEAR_stations_group = QtWidgets.QGroupBox(self.compare_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compare_SMEAR_stations_group.sizePolicy().hasHeightForWidth()
        )
        self.compare_SMEAR_stations_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compare_SMEAR_stations_group.setFont(font)
        self.compare_SMEAR_stations_group.setObjectName("compare_SMEAR_stations_group")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.compare_SMEAR_stations_group)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.compare_SMEAR_stations_list = QtWidgets.QListWidget(
            self.compare_SMEAR_stations_group
        )
        self.compare_SMEAR_stations_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.compare_SMEAR_stations_list.setWordWrap(True)
        self.compare_SMEAR_stations_list.setObjectName("compare_SMEAR_stations_list")
        self.gridLayout_14.addWidget(self.compare_SMEAR_stations_list, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.compare_SMEAR_stations_group, 3, 1, 1, 1)
        self.compare_SMEAR_years_group = QtWidgets.QGroupBox(self.compare_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.compare_SMEAR_years_group.sizePolicy().hasHeightForWidth()
        )
        self.compare_SMEAR_years_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compare_SMEAR_years_group.setFont(font)
        self.compare_SMEAR_years_group.setObjectName("compare_SMEAR_years_group")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.compare_SMEAR_years_group)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.compare_SMEAR_years_list = QtWidgets.QListWidget(
            self.compare_SMEAR_years_group
        )
        self.compare_SMEAR_years_list.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.compare_SMEAR_years_list.setWordWrap(True)
        self.compare_SMEAR_years_list.setObjectName("compare_SMEAR_years_list")
        self.gridLayout_13.addWidget(self.compare_SMEAR_years_list, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.compare_SMEAR_years_group, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.compare_reset_button = QtWidgets.QPushButton(self.compare_tab)
        self.compare_reset_button.setObjectName("compare_reset_button")
        self.horizontalLayout_3.addWidget(self.compare_reset_button)
        self.compare_fetch_button = QtWidgets.QPushButton(self.compare_tab)
        self.compare_fetch_button.setObjectName("compare_fetch_button")
        self.horizontalLayout_3.addWidget(self.compare_fetch_button)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.compare_plot = MplWidget(self.compare_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compare_plot.sizePolicy().hasHeightForWidth())
        self.compare_plot.setSizePolicy(sizePolicy)
        self.compare_plot.setAutoFillBackground(True)
        self.compare_plot.setObjectName("compare_plot")
        self.gridLayout_8.addWidget(self.compare_plot, 0, 0, 5, 1)
        self.compare_save_plot_button = QtWidgets.QPushButton(self.compare_tab)
        self.compare_save_plot_button.setEnabled(False)
        self.compare_save_plot_button.setObjectName("compare_save_plot_button")
        self.gridLayout_8.addWidget(self.compare_save_plot_button, 5, 0, 1, 1)
        self.tabWidget.addTab(self.compare_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Settings = QtGui.QAction(MainWindow)
        self.actionImport_Settings.setObjectName("actionImport_Settings")
        self.actionExport_Settings = QtGui.QAction(MainWindow)
        self.actionExport_Settings.setObjectName("actionExport_Settings")
        self.menuFile.addAction(self.actionImport_Settings)
        self.menuFile.addAction(self.actionExport_Settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Greenhouse gas monitoring"))
        self.SMEAR_gas_group.setTitle(_translate("MainWindow", "Greenhouse gas"))
        self.SMEAR_co2_radio_button.setText(_translate("MainWindow", "CO2"))
        self.SMEAR_so2_radio_button.setText(_translate("MainWindow", "SO2"))
        self.SMEAR_no_radio_button.setText(_translate("MainWindow", "NO"))
        self.SMEAR_stations_group.setTitle(_translate("MainWindow", "Stations"))
        self.SMEAR_stations_list.setSortingEnabled(True)
        self.SMEAR_time_group.setTitle(_translate("MainWindow", "Time range"))
        self.SMEAR_start_time_label.setText(_translate("MainWindow", "Starting time"))
        self.SMEAR_end_time_label.setText(_translate("MainWindow", "Ending time"))
        self.SMEAR_aggregation_group.setTitle(
            _translate("MainWindow", "Sample time aggregation")
        )
        self.SMEAR_none_radio_button.setText(_translate("MainWindow", "NONE"))
        self.SMEAR_min_radio_button.setText(_translate("MainWindow", "MIN"))
        self.SMEAR_max_radio_button.setText(_translate("MainWindow", "MAX"))
        self.SMEAR_avg_radio_button.setText(_translate("MainWindow", "AVG"))
        self.SMEAR_summary_button.setText(_translate("MainWindow", "Data summary..."))
        self.SMEAR_save_plot_button.setText(_translate("MainWindow", "Save plot..."))
        self.SMEAR_reset_button.setText(_translate("MainWindow", "Reset"))
        self.SMEAR_fetch_button.setText(_translate("MainWindow", "Fetch data"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.SMEAR_tab),
            _translate("MainWindow", "SMEAR data"),
        )
        self.STATFI_reset_button.setText(_translate("MainWindow", "Reset"))
        self.STATFI_figures_group.setTitle(_translate("MainWindow", "Figures"))
        self.STATFI_figures_list.setSortingEnabled(True)
        self.STATFI_fetch_button.setText(_translate("MainWindow", "Fetch data"))
        self.STATFI_visualization_group.setTitle(
            _translate("MainWindow", "Visualization type")
        )
        self.STATFI_bar_chart_radio_button.setText(
            _translate("MainWindow", "Bar chart")
        )
        self.STATFI_line_graph_radio_button.setText(
            _translate("MainWindow", "Line graph")
        )
        self.STATFI_years_group.setTitle(_translate("MainWindow", "Years"))
        self.STATFI_years_list.setSortingEnabled(True)
        self.STATFI_save_plot_button.setText(_translate("MainWindow", "Save plot..."))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.STATFI_tab),
            _translate("MainWindow", "STATFI data"),
        )
        self.compare_STATFI_figures_group.setTitle(
            _translate("MainWindow", "STATFI Figures")
        )
        self.compare_STATFI_figures_list.setSortingEnabled(True)
        self.compare_STATFI_years_group.setTitle(
            _translate("MainWindow", "STATFI years range")
        )
        self.compare_STATFI_years_list.setSortingEnabled(True)
        self.compare_SMEAR_gas_group.setTitle(
            _translate("MainWindow", "SMEAR greenhouse gas")
        )
        self.compare_co2_radio_button.setText(_translate("MainWindow", "CO2"))
        self.compare_so2_radio_button.setText(_translate("MainWindow", "SO2"))
        self.compare_no_radio_button.setText(_translate("MainWindow", "NO"))
        self.compare_SMEAR_stations_group.setTitle(
            _translate("MainWindow", "SMEAR Stations")
        )
        self.compare_SMEAR_stations_list.setSortingEnabled(True)
        self.compare_SMEAR_years_group.setTitle(
            _translate("MainWindow", "SMEAR years range")
        )
        self.compare_SMEAR_years_list.setSortingEnabled(True)
        self.compare_reset_button.setText(_translate("MainWindow", "Reset"))
        self.compare_fetch_button.setText(_translate("MainWindow", "Fetch data"))
        self.compare_save_plot_button.setText(_translate("MainWindow", "Save plot..."))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.compare_tab),
            _translate("MainWindow", "Compare SMEAR and STATFI"),
        )
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_Settings.setText(
            _translate("MainWindow", "&Import Settings...")
        )
        self.actionImport_Settings.setToolTip(
            _translate("MainWindow", "Import previously saved choices")
        )
        self.actionImport_Settings.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionExport_Settings.setText(
            _translate("MainWindow", "&Export Settings...")
        )
        self.actionExport_Settings.setToolTip(
            _translate("MainWindow", "Save current choices to a file")
        )
        self.actionExport_Settings.setShortcut(_translate("MainWindow", "Ctrl+E"))
