# Form implementation generated from reading ui file 'ui/SMEAR_summary_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog.resize(427, 417)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setModal(True)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 387, 376))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.daily_average_value = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.daily_average_value.setFont(font)
        self.daily_average_value.setText("")
        self.daily_average_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_average_value.setObjectName("daily_average_value")
        self.gridLayout.addWidget(self.daily_average_value, 5, 2, 1, 1)
        self.table = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.gridLayout.addWidget(self.table, 1, 0, 1, 3)
        self.daily_average_label = QtWidgets.QLabel(self.layoutWidget)
        self.daily_average_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_average_label.setObjectName("daily_average_label")
        self.gridLayout.addWidget(self.daily_average_label, 4, 2, 1, 1)
        self.table_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_label.sizePolicy().hasHeightForWidth())
        self.table_label.setSizePolicy(sizePolicy)
        self.table_label.setWordWrap(True)
        self.table_label.setObjectName("table_label")
        self.gridLayout.addWidget(self.table_label, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.daily_minimum_station = QtWidgets.QLabel(self.layoutWidget)
        self.daily_minimum_station.setText("")
        self.daily_minimum_station.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_minimum_station.setObjectName("daily_minimum_station")
        self.gridLayout.addWidget(self.daily_minimum_station, 6, 0, 1, 1)
        self.daily_maximum_value = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.daily_maximum_value.setFont(font)
        self.daily_maximum_value.setText("")
        self.daily_maximum_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_maximum_value.setObjectName("daily_maximum_value")
        self.gridLayout.addWidget(self.daily_maximum_value, 5, 1, 1, 1)
        self.daily_minimum_label = QtWidgets.QLabel(self.layoutWidget)
        self.daily_minimum_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_minimum_label.setObjectName("daily_minimum_label")
        self.gridLayout.addWidget(self.daily_minimum_label, 4, 0, 1, 1)
        self.daily_maximum_label = QtWidgets.QLabel(self.layoutWidget)
        self.daily_maximum_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_maximum_label.setObjectName("daily_maximum_label")
        self.gridLayout.addWidget(self.daily_maximum_label, 4, 1, 1, 1)
        self.daily_average_station = QtWidgets.QLabel(self.layoutWidget)
        self.daily_average_station.setText("")
        self.daily_average_station.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_average_station.setObjectName("daily_average_station")
        self.gridLayout.addWidget(self.daily_average_station, 6, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.daily_label = QtWidgets.QLabel(self.layoutWidget)
        self.daily_label.setObjectName("daily_label")
        self.horizontalLayout.addWidget(self.daily_label)
        self.daily_date_edit = QtWidgets.QDateEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.daily_date_edit.sizePolicy().hasHeightForWidth()
        )
        self.daily_date_edit.setSizePolicy(sizePolicy)
        self.daily_date_edit.setCalendarPopup(True)
        self.daily_date_edit.setObjectName("daily_date_edit")
        self.horizontalLayout.addWidget(self.daily_date_edit)
        self.daily_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.daily_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_label_2.setObjectName("daily_label_2")
        self.horizontalLayout.addWidget(self.daily_label_2)
        self.daily_station_dropdown = QtWidgets.QComboBox(self.layoutWidget)
        self.daily_station_dropdown.setObjectName("daily_station_dropdown")
        self.daily_station_dropdown.addItem("")
        self.horizontalLayout.addWidget(self.daily_station_dropdown)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 3)
        self.daily_minimum_value = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.daily_minimum_value.setFont(font)
        self.daily_minimum_value.setText("")
        self.daily_minimum_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_minimum_value.setObjectName("daily_minimum_value")
        self.gridLayout.addWidget(self.daily_minimum_value, 5, 0, 1, 1)
        self.daily_maximum_station = QtWidgets.QLabel(self.layoutWidget)
        self.daily_maximum_station.setText("")
        self.daily_maximum_station.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.daily_maximum_station.setObjectName("daily_maximum_station")
        self.gridLayout.addWidget(self.daily_maximum_station, 6, 1, 1, 1)
        self.warning = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.warning.setFont(font)
        self.warning.setText("")
        self.warning.setWordWrap(True)
        self.warning.setObjectName("warning")
        self.gridLayout.addWidget(self.warning, 7, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data summary"))
        self.daily_average_label.setText(_translate("Dialog", "Average"))
        self.table_label.setText(
            _translate(
                "Dialog",
                "Minimum, maximum and average values for chosen stations in the chosen time range",
            )
        )
        self.daily_minimum_label.setText(_translate("Dialog", "Minimum"))
        self.daily_maximum_label.setText(_translate("Dialog", "Maximum"))
        self.daily_label.setText(_translate("Dialog", "Daily aggregation"))
        self.daily_date_edit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.daily_label_2.setText(_translate("Dialog", "in"))
        self.daily_station_dropdown.setCurrentText(_translate("Dialog", "All stations"))
        self.daily_station_dropdown.setItemText(0, _translate("Dialog", "All stations"))
